### ISSUE TITLE
Roadmap 2.0

### ISSUE THREAD

**Issue by StarpTech** [hemerajs/hemera#160]
- [X] More natural and simple extensions lifecycle
- [X] Emit clientResponseError or `serverResponseError` only for middleware, extensions or fatal errors not when an error is replied by the user.
- [X] Remove support for generator functions
- [X] Remove async/await support in extensions due to performance and simplicity
- [X] Remove circuit breaker implementation
- [X] `next`has to be called explicit in the middleware
- [X] Calling `send` multiple times shouldn't have side effects
- [X] Don't abort request life cycle on business errors.
- [X] First replied error is set others are ignored
- [X] First replied value is sent others are ignored
- [X] Pass reply interface to `add` middlewares
- [X] Update all plugins to the new api
- [ ] Use github releases for changelog informations
- [X] Update docs
- [X] Remove `expose` and use prototype based `decorations`
- [X] Use [Avvio](https://github.com/mcollina/avvio) to bootstrap plugins asynchronously
- [x] Remove `req.locals`
- [X] [Graceful shutdown](https://github.com/hemerajs/hemera/tree/feature/hemera_2_0/packages/hemera-graceful-shutdown) routine as a separate plugin
- [X] Use prettier with standardjs linting rules

Plugin system is heavily inspired by https://github.com/fastify/fastify

**Comment by StarpTech** [comment]
Current working branch https://github.com/hemerajs/hemera/tree/feature/hemera_2_0

- Increased performance by ~35%

**Comment by StarpTech** [comment]
Released https://github.com/hemerajs/hemera/releases/tag/nats-hemera%402.0.0-0
